[versions]
agp = "8.8.1"
publish = "0.30.0"

[libraries]

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
