name: Build Artifacts

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.12.1

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :lib:publishToMavenLocal --stacktrace --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libunbound
          path: ~/.m2/repository/**
          if-no-files-found: error
